import Head from "next/head";
import Hero from "../components/Hero";
import homepage from "../public/heros/hero.webp";
import About from "../components/About";
import { copy } from "../public/copy/copy";
import Usp from "../components/Usp";
import Subscribe from '../components/Subscribe'
import aboutForge from "../public/about/bakers-workbench.webp";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero page={homepage} />
      <About
        h1={copy.pages[0].homepage[0].h1}
        h2={copy.pages[0].homepage[1].h2}
        p1={copy.pages[0].homepage[2].p1}
        p2={copy.pages[0].homepage[3].p2}
        image={aboutForge}
      />
      <Usp />
      <Subscribe />
    </>
  );
}
